version: "3.2"
services:
  postgres:
    image: "postgres:12.2"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_DB=meet
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
  node:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: ["npm", "start"]
  
